language: python
python:
  - 3.8
  - 3.7
  - 3.6

install: pip install tox-travis twine

script: make test

# builds both package and alias
before_deploy: make release/build
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  on:
    tags: true
    repo: AndreMiras/pyetheroll
    python: 3.7
