from enum import Enum

ROUND_DIGITS = 2
DEFAULT_GAS_PRICE_GWEI = 4
DEFAULT_GAS_PRICE_WEI = int(DEFAULT_GAS_PRICE_GWEI * 1e9)
DEFAULT_API_KEY_TOKEN = "YourApiKeyToken"


class ChainID(Enum):
    MAINNET = 1
    MORDEN = 2
    ROPSTEN = 3
